# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\football_parser.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(834, 539)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 768))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_panel = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.top_panel.sizePolicy().hasHeightForWidth())
        self.top_panel.setSizePolicy(sizePolicy)
        self.top_panel.setObjectName("top_panel")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.top_panel)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.top_panel)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.top_panel)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.ProxyEdit = QtWidgets.QLineEdit(self.top_panel)
        self.ProxyEdit.setObjectName("ProxyEdit")
        self.horizontalLayout.addWidget(self.ProxyEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_9.addLayout(self.verticalLayout_2)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.select_parse_year_cbx = QtWidgets.QComboBox(self.top_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_parse_year_cbx.sizePolicy().hasHeightForWidth())
        self.select_parse_year_cbx.setSizePolicy(sizePolicy)
        self.select_parse_year_cbx.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.select_parse_year_cbx.setObjectName("select_parse_year_cbx")
        self.horizontalLayout_5.addWidget(self.select_parse_year_cbx)
        self.LinksFromFileCbx = QtWidgets.QCheckBox(self.top_panel)
        self.LinksFromFileCbx.setObjectName("LinksFromFileCbx")
        self.horizontalLayout_5.addWidget(self.LinksFromFileCbx)
        self.LoadSeasonsBtn = QtWidgets.QPushButton(self.top_panel)
        self.LoadSeasonsBtn.setObjectName("LoadSeasonsBtn")
        self.horizontalLayout_5.addWidget(self.LoadSeasonsBtn)
        self.ParseBtn = QtWidgets.QPushButton(self.top_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ParseBtn.sizePolicy().hasHeightForWidth())
        self.ParseBtn.setSizePolicy(sizePolicy)
        self.ParseBtn.setObjectName("ParseBtn")
        self.horizontalLayout_5.addWidget(self.ParseBtn)
        self.SaveLinksBtn = QtWidgets.QPushButton(self.top_panel)
        self.SaveLinksBtn.setObjectName("SaveLinksBtn")
        self.horizontalLayout_5.addWidget(self.SaveLinksBtn)
        self.verticalLayout_13.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtWidgets.QLabel(self.top_panel)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.ParsedResultLbl = QtWidgets.QLabel(self.top_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ParsedResultLbl.sizePolicy().hasHeightForWidth())
        self.ParsedResultLbl.setSizePolicy(sizePolicy)
        self.ParsedResultLbl.setText("")
        self.ParsedResultLbl.setObjectName("ParsedResultLbl")
        self.horizontalLayout_8.addWidget(self.ParsedResultLbl)
        self.ParsingPBar = QtWidgets.QProgressBar(self.top_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ParsingPBar.sizePolicy().hasHeightForWidth())
        self.ParsingPBar.setSizePolicy(sizePolicy)
        self.ParsingPBar.setMaximum(1)
        self.ParsingPBar.setProperty("value", 0)
        self.ParsingPBar.setObjectName("ParsingPBar")
        self.horizontalLayout_8.addWidget(self.ParsingPBar)
        self.verticalLayout_13.addLayout(self.horizontalLayout_8)
        self.widget_2 = QtWidgets.QWidget(self.top_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.parse_animated_lbl = QtWidgets.QLabel(self.widget_2)
        self.parse_animated_lbl.setMaximumSize(QtCore.QSize(32, 32))
        self.parse_animated_lbl.setText("")
        self.parse_animated_lbl.setObjectName("parse_animated_lbl")
        self.horizontalLayout_3.addWidget(self.parse_animated_lbl)
        self.parse_status_lbl = QtWidgets.QLabel(self.widget_2)
        self.parse_status_lbl.setText("")
        self.parse_status_lbl.setObjectName("parse_status_lbl")
        self.horizontalLayout_3.addWidget(self.parse_status_lbl)
        self.verticalLayout_13.addWidget(self.widget_2)
        self.ParsedStatusList = QtWidgets.QListWidget(self.top_panel)
        self.ParsedStatusList.setObjectName("ParsedStatusList")
        self.verticalLayout_13.addWidget(self.ParsedStatusList)
        self.parse_info_textb = QtWidgets.QTextBrowser(self.top_panel)
        self.parse_info_textb.setObjectName("parse_info_textb")
        self.verticalLayout_13.addWidget(self.parse_info_textb)
        self.horizontalLayout_9.addLayout(self.verticalLayout_13)
        self.verticalLayout.addWidget(self.top_panel)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 834, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Parsing settings"))
        self.label_2.setText(_translate("MainWindow", "Proxy"))
        self.LinksFromFileCbx.setText(_translate("MainWindow", "IsFromFile"))
        self.LoadSeasonsBtn.setText(_translate("MainWindow", "Load seasons"))
        self.ParseBtn.setText(_translate("MainWindow", "Parse"))
        self.SaveLinksBtn.setText(_translate("MainWindow", "SaveLinks"))
        self.label.setText(_translate("MainWindow", "Parse information: "))

